[ECU1]
; Mode=0 : TCP, Mode=1 : Serial port
Mode=0
; ID='ECU1' for imx/linux and ID='SCC' for Autosar.
ECU_ID=ECU1

; Output FORMAT='0' for JSON format and FORMAT='1' for string format. Default format is DLT/string
FORMAT=1

PORT=3490
IP=172.17.0.1

COMPORT=
BAUDRATE=

; Provide path for xml/trt path for non-verbose mesasge decoding
; Kindly use forward slash '/' in TRT/XML path
FILEPATH="/usr/share/DLTConnector/default.trt"

; By default log is off,1: to switch on the log
APPDEBUG=0

; Note:: FORMAT, APPDEBUG, FILEPATH values should be same in all ECU's or else could be provided in first ECU Group only; value entries can remain empty.

[ECU2]
; Mode=0 : TCP, Mode=1 : Serial port
Mode=1
; ID='ECU1' for imx/linux and ID='SCC' for Autosar.
ECU_ID=SCC

FORMAT=

PORT=
IP=

COMPORT=COM1
BAUDRATE=115200

FILEPATH=

APPDEBUG=
